import type { Metadata } from "next";
import localFont from "next/font/local";

const gilroy = localFont({
  src: [
    {
      path: 'fonts/Gilroy-Regular.woff2',
    },
    {
      path: 'fonts/Gilroy-Medium.woff2',
    },
  ],
})

import InitColorSchemeScript from '@mui/joy/InitColorSchemeScript';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <InitColorSchemeScript />
        <title>ENIX AI</title>
      </head>
      <body className={`${gilroy.className}`}>
        {children}
      </body>
    </html>
  );
}
