import type { Metadata } from "next";
import localFont from "next/font/local";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const gilroy = localFont({
  src: [
    {
      path: "fonts/Gilroy-Regular.woff2",
    },
    {
      path: "fonts/Gilroy-Medium.woff2",
    },
  ],
});

import "./globals.css";
import ContextProvider from "@/providers/contextProvider";

export const metadata: Metadata = {
  title: "Enix AI Assistent",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!routing.locales.includes(locale as "uz" | "ru")) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <ContextProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="/favicon.ico" sizes="any" />
          <title>ENIX AI</title>
        </head>
        <body className={`${gilroy.className}`}>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
    </ContextProvider>
  );
}
