import type { Metadata } from "next";
import localFont from "next/font/local";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const gilroy = localFont({
  src: [
    {
      path: 'fonts/Gilroy-Regular.woff2',
    },
    {
      path: 'fonts/Gilroy-Medium.woff2',
    },
  ],
})

import InitColorSchemeScript from '@mui/joy/InitColorSchemeScript';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!routing.locales.includes(locale as "uz" | "ru")) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <InitColorSchemeScript />
        <title>ENIX AI</title>
      </head>
      <body className={`${gilroy.className}`}>
        <NextIntlClientProvider messages={messages}>
        {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
